'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck, Sparkles } from 'lucide-react';
import { useAuth } from '@/components/auth-provider';

const API = process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:8000';
export default function LoginPage() {
  const { signIn } = useAuth(); const [mode, setMode] = useState('login');
  const [form, setForm] = useState({ email: '', password: '', name: '' }); const [show, setShow] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(''); if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(form.email)) return setError('Enter a valid email address.'); if (form.password.length < 8) return setError('Password must be at least 8 characters.'); setBusy(true);
    try { const res = await fetch(`${API}/api/auth/${mode}`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ ...form, email: form.email.trim() }) }); const data = await res.json(); if (!res.ok) throw new Error(typeof data.detail === 'string' ? data.detail : 'Check your email and password requirements.'); signIn(data.access_token); } catch (e) { setError(e.message); } finally { setBusy(false); }
  };
  return <main className="auth-page"><div className="auth-orb orb-one"/><div className="auth-orb orb-two"/><section className="auth-showcase"><Link href="/login" className="auth-logo"><Image src="/dcare-ai-logo.png" alt="DCare AI" width={210} height={48}/></Link><div className="auth-copy"><span className="auth-eyebrow"><Sparkles size={14}/> PERSONALIZED CARE, REIMAGINED</span><h1>Your health story deserves a smarter workspace.</h1><p>Securely manage diabetes insights, retinal screenings, wound healing, and nutrition plans in one calm, clear place.</p><div className="auth-points"><span><ShieldCheck size={18}/> Encrypted health workspace</span><span><Sparkles size={18}/> AI-assisted insights for your care team</span></div></div><small className="auth-footnote">© 2026 DiaCare AI · Research project</small></section><section className="auth-panel glass-panel"><div className="auth-panel-head"><div><p className="auth-kicker">SECURE ACCESS</p><h2>{mode === 'login' ? 'Welcome back' : 'Create your account'}</h2><p>{mode === 'login' ? 'Sign in to continue to your health workspace.' : 'Start your personalized care journey.'}</p></div></div><form onSubmit={submit} noValidate>{mode === 'register' && <label>Full name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Alex Morgan" required/></label>}<label>Email address<div className="auth-input"><Mail size={17}/><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com" required/></div></label><label>Password<div className="auth-input"><LockKeyhole size={17}/><input type={show?'text':'password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="At least 8 characters" minLength={8} required/><button type="button" onClick={()=>setShow(!show)} aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{mode==='login' && <div className="auth-options"><label className="check"><input type="checkbox"/> Remember me</label><button type="button" className="auth-link">Forgot password?</button></div>}{error && <p className="auth-error" role="alert">{error}</p>}<button className="auth-submit" disabled={busy}>{busy?'Securing access…':mode==='login'?'Sign in':'Create account'}<ArrowRight size={18}/></button></form><p className="auth-switch">{mode==='login'?'New to DiaCare AI?':'Already have an account?'} <button onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Create an account':'Sign in'}</button></p></section></main>;
}
